/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AvatarImageResponse } from './AvatarImageResponse';
import {
    AvatarImageResponseFromJSON,
    AvatarImageResponseFromJSONTyped,
    AvatarImageResponseToJSON,
    AvatarImageResponseToJSONTyped,
} from './AvatarImageResponse';
import type { CourseAvatarSlot } from './CourseAvatarSlot';
import {
    CourseAvatarSlotFromJSON,
    CourseAvatarSlotFromJSONTyped,
    CourseAvatarSlotToJSON,
    CourseAvatarSlotToJSONTyped,
} from './CourseAvatarSlot';
import type { AvatarAudioResponse } from './AvatarAudioResponse';
import {
    AvatarAudioResponseFromJSON,
    AvatarAudioResponseFromJSONTyped,
    AvatarAudioResponseToJSON,
    AvatarAudioResponseToJSONTyped,
} from './AvatarAudioResponse';

/**
 * 
 * @export
 * @interface AvatarCreatedResponse
 */
export interface AvatarCreatedResponse {
    /**
     * 
     * @type {string}
     * @memberof AvatarCreatedResponse
     */
    avatarId: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarCreatedResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AvatarCreatedResponse
     */
    courseId?: string | null;
    /**
     * 
     * @type {CourseAvatarSlot}
     * @memberof AvatarCreatedResponse
     */
    slot?: CourseAvatarSlot;
    /**
     * 
     * @type {Date}
     * @memberof AvatarCreatedResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {AvatarImageResponse}
     * @memberof AvatarCreatedResponse
     */
    image: AvatarImageResponse;
    /**
     * 
     * @type {AvatarAudioResponse}
     * @memberof AvatarCreatedResponse
     */
    audio: AvatarAudioResponse;
}



/**
 * Check if a given object implements the AvatarCreatedResponse interface.
 */
export function instanceOfAvatarCreatedResponse(value: object): value is AvatarCreatedResponse {
    if (!('avatarId' in value) || value['avatarId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('audio' in value) || value['audio'] === undefined) return false;
    return true;
}

export function AvatarCreatedResponseFromJSON(json: any): AvatarCreatedResponse {
    return AvatarCreatedResponseFromJSONTyped(json, false);
}

export function AvatarCreatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarCreatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarId': json['avatarId'],
        'name': json['name'] == null ? undefined : json['name'],
        'courseId': json['courseId'] == null ? undefined : json['courseId'],
        'slot': json['slot'] == null ? undefined : CourseAvatarSlotFromJSON(json['slot']),
        'createdAt': (new Date(json['createdAt'])),
        'image': AvatarImageResponseFromJSON(json['image']),
        'audio': AvatarAudioResponseFromJSON(json['audio']),
    };
}

export function AvatarCreatedResponseToJSON(json: any): AvatarCreatedResponse {
    return AvatarCreatedResponseToJSONTyped(json, false);
}

export function AvatarCreatedResponseToJSONTyped(value?: AvatarCreatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatarId': value['avatarId'],
        'name': value['name'],
        'courseId': value['courseId'],
        'slot': CourseAvatarSlotToJSON(value['slot']),
        'createdAt': ((value['createdAt']).toISOString()),
        'image': AvatarImageResponseToJSON(value['image']),
        'audio': AvatarAudioResponseToJSON(value['audio']),
    };
}

