/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvatarAudioResponse
 */
export interface AvatarAudioResponse {
    /**
     * 
     * @type {string}
     * @memberof AvatarAudioResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarAudioResponse
     */
    avatarId: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarAudioResponse
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarAudioResponse
     */
    mimeType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AvatarAudioResponse
     */
    sizeBytes?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AvatarAudioResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the AvatarAudioResponse interface.
 */
export function instanceOfAvatarAudioResponse(value: object): value is AvatarAudioResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('avatarId' in value) || value['avatarId'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AvatarAudioResponseFromJSON(json: any): AvatarAudioResponse {
    return AvatarAudioResponseFromJSONTyped(json, false);
}

export function AvatarAudioResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarAudioResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'avatarId': json['avatarId'],
        'filePath': json['filePath'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function AvatarAudioResponseToJSON(json: any): AvatarAudioResponse {
    return AvatarAudioResponseToJSONTyped(json, false);
}

export function AvatarAudioResponseToJSONTyped(value?: AvatarAudioResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'avatarId': value['avatarId'],
        'filePath': value['filePath'],
        'mimeType': value['mimeType'],
        'sizeBytes': value['sizeBytes'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

