/* tslint:disable */
/* eslint-disable */
/**
 * Avatar Generation Service API
 * API for the Orpheus video generation. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" 
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvatarCreatedResponseImage
 */
export interface AvatarCreatedResponseImage {
    /**
     * 
     * @type {string}
     * @memberof AvatarCreatedResponseImage
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarCreatedResponseImage
     */
    filePath?: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarCreatedResponseImage
     */
    mimeType?: string;
    /**
     * 
     * @type {number}
     * @memberof AvatarCreatedResponseImage
     */
    sizeBytes?: number;
    /**
     * 
     * @type {Date}
     * @memberof AvatarCreatedResponseImage
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the AvatarCreatedResponseImage interface.
 */
export function instanceOfAvatarCreatedResponseImage(value: object): value is AvatarCreatedResponseImage {
    return true;
}

export function AvatarCreatedResponseImageFromJSON(json: any): AvatarCreatedResponseImage {
    return AvatarCreatedResponseImageFromJSONTyped(json, false);
}

export function AvatarCreatedResponseImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarCreatedResponseImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'filePath': json['filePath'] == null ? undefined : json['filePath'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function AvatarCreatedResponseImageToJSON(json: any): AvatarCreatedResponseImage {
    return AvatarCreatedResponseImageToJSONTyped(json, false);
}

export function AvatarCreatedResponseImageToJSONTyped(value?: AvatarCreatedResponseImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'filePath': value['filePath'],
        'mimeType': value['mimeType'],
        'sizeBytes': value['sizeBytes'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

