/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvatarImageResponse
 */
export interface AvatarImageResponse {
    /**
     * 
     * @type {string}
     * @memberof AvatarImageResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarImageResponse
     */
    avatarId: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarImageResponse
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof AvatarImageResponse
     */
    mimeType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AvatarImageResponse
     */
    sizeBytes?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof AvatarImageResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the AvatarImageResponse interface.
 */
export function instanceOfAvatarImageResponse(value: object): value is AvatarImageResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('avatarId' in value) || value['avatarId'] === undefined) return false;
    if (!('filePath' in value) || value['filePath'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function AvatarImageResponseFromJSON(json: any): AvatarImageResponse {
    return AvatarImageResponseFromJSONTyped(json, false);
}

export function AvatarImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'avatarId': json['avatarId'],
        'filePath': json['filePath'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function AvatarImageResponseToJSON(json: any): AvatarImageResponse {
    return AvatarImageResponseToJSONTyped(json, false);
}

export function AvatarImageResponseToJSONTyped(value?: AvatarImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'avatarId': value['avatarId'],
        'filePath': value['filePath'],
        'mimeType': value['mimeType'],
        'sizeBytes': value['sizeBytes'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

