/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerationAcceptedResponse
 */
export interface GenerationAcceptedResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerationAcceptedResponse
     */
    promptId: string;
    /**
     * 
     * @type {Date}
     * @memberof GenerationAcceptedResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the GenerationAcceptedResponse interface.
 */
export function instanceOfGenerationAcceptedResponse(value: object): value is GenerationAcceptedResponse {
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function GenerationAcceptedResponseFromJSON(json: any): GenerationAcceptedResponse {
    return GenerationAcceptedResponseFromJSONTyped(json, false);
}

export function GenerationAcceptedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationAcceptedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promptId': json['promptId'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function GenerationAcceptedResponseToJSON(json: any): GenerationAcceptedResponse {
    return GenerationAcceptedResponseToJSONTyped(json, false);
}

export function GenerationAcceptedResponseToJSONTyped(value?: GenerationAcceptedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptId': value['promptId'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

