/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * API for the Orpheus video generation. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" 
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Returned immediately after generation request accepted
 * @export
 * @interface GenerationAcceptedResponse
 */
export interface GenerationAcceptedResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerationAcceptedResponse
     */
    promptId?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerationAcceptedResponse
     */
    status?: GenerationAcceptedResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof GenerationAcceptedResponse
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const GenerationAcceptedResponseStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Failed: 'FAILED',
    Done: 'DONE'
} as const;
export type GenerationAcceptedResponseStatusEnum = typeof GenerationAcceptedResponseStatusEnum[keyof typeof GenerationAcceptedResponseStatusEnum];


/**
 * Check if a given object implements the GenerationAcceptedResponse interface.
 */
export function instanceOfGenerationAcceptedResponse(value: object): value is GenerationAcceptedResponse {
    return true;
}

export function GenerationAcceptedResponseFromJSON(json: any): GenerationAcceptedResponse {
    return GenerationAcceptedResponseFromJSONTyped(json, false);
}

export function GenerationAcceptedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationAcceptedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promptId': json['promptId'] == null ? undefined : json['promptId'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function GenerationAcceptedResponseToJSON(json: any): GenerationAcceptedResponse {
    return GenerationAcceptedResponseToJSONTyped(json, false);
}

export function GenerationAcceptedResponseToJSONTyped(value?: GenerationAcceptedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptId': value['promptId'],
        'status': value['status'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

