/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
    UserProfileToJSONTyped,
} from './UserProfile';

/**
 * 
 * @export
 * @interface GenerateRequest
 */
export interface GenerateRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateRequest
     */
    voiceTrack: string;
    /**
     * 
     * @type {number}
     * @memberof GenerateRequest
     */
    slideNumber: number;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequest
     */
    promptId: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequest
     */
    courseId: string;
    /**
     * 
     * @type {UserProfile}
     * @memberof GenerateRequest
     */
    userProfile: UserProfile;
    /**
     * 
     * @type {string}
     * @memberof GenerateRequest
     */
    slot?: GenerateRequestSlotEnum;
}


/**
 * @export
 */
export const GenerateRequestSlotEnum = {
    Default: 'default',
    Beginning: 'beginning',
    Ending: 'ending'
} as const;
export type GenerateRequestSlotEnum = typeof GenerateRequestSlotEnum[keyof typeof GenerateRequestSlotEnum];


/**
 * Check if a given object implements the GenerateRequest interface.
 */
export function instanceOfGenerateRequest(value: object): value is GenerateRequest {
    if (!('voiceTrack' in value) || value['voiceTrack'] === undefined) return false;
    if (!('slideNumber' in value) || value['slideNumber'] === undefined) return false;
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('userProfile' in value) || value['userProfile'] === undefined) return false;
    return true;
}

export function GenerateRequestFromJSON(json: any): GenerateRequest {
    return GenerateRequestFromJSONTyped(json, false);
}

export function GenerateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'voiceTrack': json['voiceTrack'],
        'slideNumber': json['slideNumber'],
        'promptId': json['promptId'],
        'courseId': json['courseId'],
        'userProfile': UserProfileFromJSON(json['userProfile']),
        'slot': json['slot'] == null ? undefined : json['slot'],
    };
}

export function GenerateRequestToJSON(json: any): GenerateRequest {
    return GenerateRequestToJSONTyped(json, false);
}

export function GenerateRequestToJSONTyped(value?: GenerateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'voiceTrack': value['voiceTrack'],
        'slideNumber': value['slideNumber'],
        'promptId': value['promptId'],
        'courseId': value['courseId'],
        'userProfile': UserProfileToJSON(value['userProfile']),
        'slot': value['slot'],
    };
}

