/* tslint:disable */
/* eslint-disable */
/**
 * Avatar Generation Service API
 * API for the Orpheus video generation. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" 
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerationStatusResponse
 */
export interface GenerationStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    promptId?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    status?: GenerationStatusResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof GenerationStatusResponse
     */
    lastUpdated?: Date;
    /**
     * URL even if not ready
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    resultUrl?: string;
    /**
     * 0 when DONE/FAILED
     * @type {number}
     * @memberof GenerationStatusResponse
     */
    estimatedSecondsLeft?: number;
    /**
     * 
     * @type {Error}
     * @memberof GenerationStatusResponse
     */
    error?: Error;
}


/**
 * @export
 */
export const GenerationStatusResponseStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Failed: 'FAILED',
    Done: 'DONE'
} as const;
export type GenerationStatusResponseStatusEnum = typeof GenerationStatusResponseStatusEnum[keyof typeof GenerationStatusResponseStatusEnum];


/**
 * Check if a given object implements the GenerationStatusResponse interface.
 */
export function instanceOfGenerationStatusResponse(value: object): value is GenerationStatusResponse {
    return true;
}

export function GenerationStatusResponseFromJSON(json: any): GenerationStatusResponse {
    return GenerationStatusResponseFromJSONTyped(json, false);
}

export function GenerationStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promptId': json['promptId'] == null ? undefined : json['promptId'],
        'status': json['status'] == null ? undefined : json['status'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : (new Date(json['lastUpdated'])),
        'resultUrl': json['resultUrl'] == null ? undefined : json['resultUrl'],
        'estimatedSecondsLeft': json['estimatedSecondsLeft'] == null ? undefined : json['estimatedSecondsLeft'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GenerationStatusResponseToJSON(json: any): GenerationStatusResponse {
    return GenerationStatusResponseToJSONTyped(json, false);
}

export function GenerationStatusResponseToJSONTyped(value?: GenerationStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptId': value['promptId'],
        'status': value['status'],
        'lastUpdated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
        'resultUrl': value['resultUrl'],
        'estimatedSecondsLeft': value['estimatedSecondsLeft'],
        'error': value['error'],
    };
}

