/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorModel } from './ErrorModel';
import {
    ErrorModelFromJSON,
    ErrorModelFromJSONTyped,
    ErrorModelToJSON,
    ErrorModelToJSONTyped,
} from './ErrorModel';

/**
 * 
 * @export
 * @interface GenerationStatusResponse
 */
export interface GenerationStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    promptId: string;
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    status: GenerationStatusResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof GenerationStatusResponse
     */
    lastUpdated: Date;
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    resultUrl: string;
    /**
     * 
     * @type {number}
     * @memberof GenerationStatusResponse
     */
    estimatedSecondsLeft: number;
    /**
     * 
     * @type {ErrorModel}
     * @memberof GenerationStatusResponse
     */
    error?: ErrorModel | null;
}


/**
 * @export
 */
export const GenerationStatusResponseStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Failed: 'FAILED',
    Done: 'DONE'
} as const;
export type GenerationStatusResponseStatusEnum = typeof GenerationStatusResponseStatusEnum[keyof typeof GenerationStatusResponseStatusEnum];


/**
 * Check if a given object implements the GenerationStatusResponse interface.
 */
export function instanceOfGenerationStatusResponse(value: object): value is GenerationStatusResponse {
    if (!('promptId' in value) || value['promptId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    if (!('resultUrl' in value) || value['resultUrl'] === undefined) return false;
    if (!('estimatedSecondsLeft' in value) || value['estimatedSecondsLeft'] === undefined) return false;
    return true;
}

export function GenerationStatusResponseFromJSON(json: any): GenerationStatusResponse {
    return GenerationStatusResponseFromJSONTyped(json, false);
}

export function GenerationStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promptId': json['promptId'],
        'status': json['status'],
        'lastUpdated': (new Date(json['lastUpdated'])),
        'resultUrl': json['resultUrl'],
        'estimatedSecondsLeft': json['estimatedSecondsLeft'],
        'error': json['error'] == null ? undefined : ErrorModelFromJSON(json['error']),
    };
}

export function GenerationStatusResponseToJSON(json: any): GenerationStatusResponse {
    return GenerationStatusResponseToJSONTyped(json, false);
}

export function GenerationStatusResponseToJSONTyped(value?: GenerationStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptId': value['promptId'],
        'status': value['status'],
        'lastUpdated': ((value['lastUpdated']).toISOString()),
        'resultUrl': value['resultUrl'],
        'estimatedSecondsLeft': value['estimatedSecondsLeft'],
        'error': ErrorModelToJSON(value['error']),
    };
}

