/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Preferences
 */
export interface Preferences {
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    answerLength?: PreferencesAnswerLengthEnum | null;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    languageLevel?: PreferencesLanguageLevelEnum | null;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    expertiseLevel?: PreferencesExpertiseLevelEnum | null;
    /**
     * 
     * @type {string}
     * @memberof Preferences
     */
    includePictures?: PreferencesIncludePicturesEnum | null;
}


/**
 * @export
 */
export const PreferencesAnswerLengthEnum = {
    Short: 'short',
    Medium: 'medium',
    Long: 'long'
} as const;
export type PreferencesAnswerLengthEnum = typeof PreferencesAnswerLengthEnum[keyof typeof PreferencesAnswerLengthEnum];

/**
 * @export
 */
export const PreferencesLanguageLevelEnum = {
    Basic: 'basic',
    Intermediate: 'intermediate',
    Advanced: 'advanced'
} as const;
export type PreferencesLanguageLevelEnum = typeof PreferencesLanguageLevelEnum[keyof typeof PreferencesLanguageLevelEnum];

/**
 * @export
 */
export const PreferencesExpertiseLevelEnum = {
    Beginner: 'beginner',
    Intermediate: 'intermediate',
    Advanced: 'advanced',
    Expert: 'expert'
} as const;
export type PreferencesExpertiseLevelEnum = typeof PreferencesExpertiseLevelEnum[keyof typeof PreferencesExpertiseLevelEnum];

/**
 * @export
 */
export const PreferencesIncludePicturesEnum = {
    None: 'none',
    Few: 'few',
    Many: 'many'
} as const;
export type PreferencesIncludePicturesEnum = typeof PreferencesIncludePicturesEnum[keyof typeof PreferencesIncludePicturesEnum];


/**
 * Check if a given object implements the Preferences interface.
 */
export function instanceOfPreferences(value: object): value is Preferences {
    return true;
}

export function PreferencesFromJSON(json: any): Preferences {
    return PreferencesFromJSONTyped(json, false);
}

export function PreferencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Preferences {
    if (json == null) {
        return json;
    }
    return {
        
        'answerLength': json['answerLength'] == null ? undefined : json['answerLength'],
        'languageLevel': json['languageLevel'] == null ? undefined : json['languageLevel'],
        'expertiseLevel': json['expertiseLevel'] == null ? undefined : json['expertiseLevel'],
        'includePictures': json['includePictures'] == null ? undefined : json['includePictures'],
    };
}

export function PreferencesToJSON(json: any): Preferences {
    return PreferencesToJSONTyped(json, false);
}

export function PreferencesToJSONTyped(value?: Preferences | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answerLength': value['answerLength'],
        'languageLevel': value['languageLevel'],
        'expertiseLevel': value['expertiseLevel'],
        'includePictures': value['includePictures'],
    };
}

