/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Preferences } from './Preferences';
import {
    PreferencesFromJSON,
    PreferencesFromJSONTyped,
    PreferencesToJSON,
    PreferencesToJSONTyped,
} from './Preferences';

/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    role: UserProfileRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    language: UserProfileLanguageEnum;
    /**
     * 
     * @type {Preferences}
     * @memberof UserProfile
     */
    preferences?: Preferences | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserProfile
     */
    enrolledCourses?: Array<string> | null;
}


/**
 * @export
 */
export const UserProfileRoleEnum = {
    Student: 'student',
    Instructor: 'instructor'
} as const;
export type UserProfileRoleEnum = typeof UserProfileRoleEnum[keyof typeof UserProfileRoleEnum];

/**
 * @export
 */
export const UserProfileLanguageEnum = {
    German: 'german',
    English: 'english'
} as const;
export type UserProfileLanguageEnum = typeof UserProfileLanguageEnum[keyof typeof UserProfileLanguageEnum];


/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'language': json['language'],
        'preferences': json['preferences'] == null ? undefined : PreferencesFromJSON(json['preferences']),
        'enrolledCourses': json['enrolled_courses'] == null ? undefined : json['enrolled_courses'],
    };
}

export function UserProfileToJSON(json: any): UserProfile {
    return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(value?: UserProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'language': value['language'],
        'preferences': PreferencesToJSON(value['preferences']),
        'enrolled_courses': value['enrolledCourses'],
    };
}

