# coding: utf-8

# flake8: noqa
"""
    Answer Generation Service API

    API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from service_slides.clients.status.models.avatar_element_status import AvatarElementStatus
from service_slides.clients.status.models.avatar_element_status_patch import AvatarElementStatusPatch
from service_slides.clients.status.models.error import Error
from service_slides.clients.status.models.slide_item import SlideItem
from service_slides.clients.status.models.slide_structure import SlideStructure
from service_slides.clients.status.models.status import Status
from service_slides.clients.status.models.status_patch import StatusPatch
from service_slides.clients.status.models.step_status import StepStatus
