# coding: utf-8

"""
    Answer Generation Service API

    API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from service_slides.clients.status.models.slide_structure import SlideStructure
from service_slides.clients.status.models.step_status import StepStatus
from typing import Optional, Set
from typing_extensions import Self

class StatusPatch(BaseModel):
    """
    StatusPatch
    """ # noqa: E501
    step_understanding: Optional[StepStatus] = Field(default=None, alias="stepUnderstanding")
    step_lookup: Optional[StepStatus] = Field(default=None, alias="stepLookup")
    step_lecture_script_generation: Optional[StepStatus] = Field(default=None, alias="stepLectureScriptGeneration")
    step_slide_structure_generation: Optional[StepStatus] = Field(default=None, alias="stepSlideStructureGeneration")
    step_slide_generation: Optional[StrictInt] = Field(default=None, alias="stepSlideGeneration")
    step_slide_postprocessing: Optional[StepStatus] = Field(default=None, alias="stepSlidePostprocessing")
    steps_avatar_generation: Optional[Dict[str, Any]] = Field(default=None, alias="stepsAvatarGeneration")
    lecture_summary: Optional[StrictStr] = Field(default=None, alias="lectureSummary")
    slide_structure: Optional[SlideStructure] = Field(default=None, alias="slideStructure")
    __properties: ClassVar[List[str]] = ["stepUnderstanding", "stepLookup", "stepLectureScriptGeneration", "stepSlideStructureGeneration", "stepSlideGeneration", "stepSlidePostprocessing", "stepsAvatarGeneration", "lectureSummary", "slideStructure"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StatusPatch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of slide_structure
        if self.slide_structure:
            _dict['slideStructure'] = self.slide_structure.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StatusPatch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "stepUnderstanding": obj.get("stepUnderstanding"),
            "stepLookup": obj.get("stepLookup"),
            "stepLectureScriptGeneration": obj.get("stepLectureScriptGeneration"),
            "stepSlideStructureGeneration": obj.get("stepSlideStructureGeneration"),
            "stepSlideGeneration": obj.get("stepSlideGeneration"),
            "stepSlidePostprocessing": obj.get("stepSlidePostprocessing"),
            "stepsAvatarGeneration": obj.get("stepsAvatarGeneration"),
            "lectureSummary": obj.get("lectureSummary"),
            "slideStructure": SlideStructure.from_dict(obj["slideStructure"]) if obj.get("slideStructure") is not None else None
        })
        return _obj


