services:
  # slides-service:
  #   container_name: slides
  #   build:
  #     context: ./slides
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./slides/.env
  #   ports:
  #     - "30606:30606"
  #   networks:
  #     - orpheus

  # ui-service:
  #   container_name: ui
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - orpheus
  #   depends_on:
  #     - slides-service

  docint-app:
    container_name: docint
    build:
      context: ./document-intelligence
      dockerfile: Dockerfile
    env_file:
      - ./document-intelligence/.env
    ports:
      - "25565:25565"
    networks:
      - orpheus


  service-core:
    container_name: core
    build: 
      context: ./core
      dockerfile: Dockerfile
    env_file:
      - ./core/.env
    ports:
      - "8000:8000"
    networks:
      - orpheus
    depends_on:
      - docint-app
      
networks:
  orpheus: