version: "3.9"

volumes:
  avatar_file_storage: {}

networks:
  avatar_network: {}

services:
  # Responsibility: nginx
  avatar-video-assets:
    build:
      context: ../assets
      dockerfile: Dockerfile
    volumes:
      - avatar_file_storage:/data
    networks: [avatar_network]
    ports:
      - "8080:80"

  # Responsibility: main.py
  avatar-video-producer:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      VIDEO_ROOT: "/data/jobs"
      PUBLIC_VIDEOS_BASE: "/videos/jobs"
      GEN_AUDIO: "https://gpu.aet.cit.tum.de/avatar/audio/v1/audio/generate"
      GEN_VIDEO: "https://gpu.aet.cit.tum.de/avatar/video/infer"
    volumes:
      - avatar_file_storage:/data
    networks: [avatar_network]
    ports:
      - "9000:9000"
    depends_on:
      - avatar-video-assets
