version: "3.9"

volumes:
  video_files: {}

networks:
  core: {}

services:
  video-producer:  # running the main application
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - video_files:/data
    networks: [core]
    ports:
      - "9000:9000"  # expose API (optional in dev)
    depends_on:
      - video-assets

  video-assets:  # running NGINX
    build:
      context: ../assets
      dockerfile: Dockerfile
    volumes:
      - video_files:/srv/assets:ro
    networks: [core]
    ports:
      - "8080:80"  # expose NGINX (only in dev)
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/healthz || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3

  voice-generation:  # running TTS
    build:
      context: ../OpenVoice
      dockerfile: Dockerfile
    environment:
      - PORT=7000  # check in docker desktop
    volumes:
      - video_files:/data
    networks: [ core ]
    expose:
      - "7000"  # check in docker desktop
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:7000/healthz || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: on-failure

  avatar-generation:
    build:
      context: ../ditto-talkinghead
      dockerfile: Dockerfile
    environment:
      - PORT=7002  # check in docker desktop
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - video_files:/data
    networks: [ core ]
    expose:
      - "7002"  # check in Docker Desktop
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:7002/healthz || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: on-failure
    runtime: nvidia
