version: "3.9"

volumes:
  file_storage: {}

networks:
  local-core: {}

services:
  # Responsibility: nginx
  video-assets:
    build:
      context: ../assets
      dockerfile: Dockerfile
    volumes:
      - file_storage:/data
    networks: [local-core]
    ports:
      - "8080:80"

  # Responsibility: main.py
  video-producer:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      VIDEO_ROOT: "/data/jobs"
      PUBLIC_VIDEOS_BASE: "/videos/jobs"
      GEN_AUDIO: "https://gpu.aet.cit.tum.de/avatar/audio/v1/audio/generate"
      GEN_VIDEO: "https://gpu.aet.cit.tum.de/avatar/video/infer"
    volumes:
      - file_storage:/data
    networks: [local-core]
    ports:
      - "9000:9000"
    depends_on:
      - video-assets
