version: "3.9"

volumes:
  file_storage: {}
  # /data in all containers
  # /data/examples is a copy of example folder

networks:
  core: {}

services:
  example:
    image: busybox
    volumes:
      - file_storage:/data
      - ../ditto-talkinghead/example:/seed:ro
    command: >
      sh -c 'set -e;
      if [ ! -f /data/.seed_done ]; then
        mkdir -p /data/example &&
        cp -a /seed/. /data/example &&
        echo done > /data/.seed_done;
      fi'
    restart: "no"
    networks: [core]

  video-assets:
    build:
      context: ../assets
      dockerfile: Dockerfile
    volumes:
      - file_storage:/data
    networks: [core]
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 20s

  voice-generation:
    build:
      context: ../OpenVoice
      dockerfile: Dockerfile
    volumes:
      - file_storage:/data
    networks: [core]
    expose:
      - "7000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    restart: on-failure
    depends_on:
      example:
        condition: service_completed_successfully

  avatar-generation:
    build:
      context: ../ditto-talkinghead
      dockerfile: Dockerfile
    volumes:
      - file_storage:/data
    networks: [core]
    expose:
      - "8000"  # see docker file in ditto-talkinghead
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: on-failure
    gpus: all
    depends_on:
      example:
        condition: service_completed_successfully

  video-producer:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - file_storage:/data
    networks: [core]
    ports:
      - "9000:9000"
    depends_on:
      example:
        condition: service_completed_successfully
      video-assets:
        condition: service_healthy
