/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AvatarCreatedResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AvatarCreatedResponseFromJSON,
    AvatarCreatedResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateAvatarV1AvatarsPostRequest {
    courseId: string;
    imageFile: Blob;
    audioFile: Blob;
    name?: string | null;
    slot?: string | null;
}

export interface GetAvatarsByCourseEndpointV1AvatarsByCourseCourseIdGetRequest {
    courseId: string;
    slot?: string | null;
}

export interface ReplaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPostRequest {
    courseId: string;
    slot: string;
    audioFile: Blob;
}

export interface ReplaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePostRequest {
    courseId: string;
    slot: string;
    imageFile: Blob;
}

/**
 * 
 */
export class AvatarApi extends runtime.BaseAPI {

    /**
     * Create Avatar
     */
    async createAvatarV1AvatarsPostRaw(requestParameters: CreateAvatarV1AvatarsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AvatarCreatedResponse>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling createAvatarV1AvatarsPost().'
            );
        }

        if (requestParameters['imageFile'] == null) {
            throw new runtime.RequiredError(
                'imageFile',
                'Required parameter "imageFile" was null or undefined when calling createAvatarV1AvatarsPost().'
            );
        }

        if (requestParameters['audioFile'] == null) {
            throw new runtime.RequiredError(
                'audioFile',
                'Required parameter "audioFile" was null or undefined when calling createAvatarV1AvatarsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['name'] != null) {
            formParams.append('name', requestParameters['name'] as any);
        }

        if (requestParameters['courseId'] != null) {
            formParams.append('courseId', requestParameters['courseId'] as any);
        }

        if (requestParameters['slot'] != null) {
            formParams.append('slot', requestParameters['slot'] as any);
        }

        if (requestParameters['imageFile'] != null) {
            formParams.append('image_file', requestParameters['imageFile'] as any);
        }

        if (requestParameters['audioFile'] != null) {
            formParams.append('audio_file', requestParameters['audioFile'] as any);
        }


        let urlPath = `/v1/avatars`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AvatarCreatedResponseFromJSON(jsonValue));
    }

    /**
     * Create Avatar
     */
    async createAvatarV1AvatarsPost(requestParameters: CreateAvatarV1AvatarsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AvatarCreatedResponse> {
        const response = await this.createAvatarV1AvatarsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Avatars By Course Endpoint
     */
    async getAvatarsByCourseEndpointV1AvatarsByCourseCourseIdGetRaw(requestParameters: GetAvatarsByCourseEndpointV1AvatarsByCourseCourseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AvatarCreatedResponse>>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling getAvatarsByCourseEndpointV1AvatarsByCourseCourseIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['slot'] != null) {
            queryParameters['slot'] = requestParameters['slot'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/avatars/by-course/{courseId}`;
        urlPath = urlPath.replace(`{${"courseId"}}`, encodeURIComponent(String(requestParameters['courseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AvatarCreatedResponseFromJSON));
    }

    /**
     * Get Avatars By Course Endpoint
     */
    async getAvatarsByCourseEndpointV1AvatarsByCourseCourseIdGet(requestParameters: GetAvatarsByCourseEndpointV1AvatarsByCourseCourseIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AvatarCreatedResponse>> {
        const response = await this.getAvatarsByCourseEndpointV1AvatarsByCourseCourseIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replace Avatar Audio Endpoint
     */
    async replaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPostRaw(requestParameters: ReplaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AvatarCreatedResponse>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling replaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPost().'
            );
        }

        if (requestParameters['slot'] == null) {
            throw new runtime.RequiredError(
                'slot',
                'Required parameter "slot" was null or undefined when calling replaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPost().'
            );
        }

        if (requestParameters['audioFile'] == null) {
            throw new runtime.RequiredError(
                'audioFile',
                'Required parameter "audioFile" was null or undefined when calling replaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['audioFile'] != null) {
            formParams.append('audio_file', requestParameters['audioFile'] as any);
        }


        let urlPath = `/v1/avatars/{courseId}/{slot}/audio`;
        urlPath = urlPath.replace(`{${"courseId"}}`, encodeURIComponent(String(requestParameters['courseId'])));
        urlPath = urlPath.replace(`{${"slot"}}`, encodeURIComponent(String(requestParameters['slot'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AvatarCreatedResponseFromJSON(jsonValue));
    }

    /**
     * Replace Avatar Audio Endpoint
     */
    async replaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPost(requestParameters: ReplaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AvatarCreatedResponse> {
        const response = await this.replaceAvatarAudioEndpointV1AvatarsCourseIdSlotAudioPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replace Avatar Image Endpoint
     */
    async replaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePostRaw(requestParameters: ReplaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AvatarCreatedResponse>> {
        if (requestParameters['courseId'] == null) {
            throw new runtime.RequiredError(
                'courseId',
                'Required parameter "courseId" was null or undefined when calling replaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePost().'
            );
        }

        if (requestParameters['slot'] == null) {
            throw new runtime.RequiredError(
                'slot',
                'Required parameter "slot" was null or undefined when calling replaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePost().'
            );
        }

        if (requestParameters['imageFile'] == null) {
            throw new runtime.RequiredError(
                'imageFile',
                'Required parameter "imageFile" was null or undefined when calling replaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['imageFile'] != null) {
            formParams.append('image_file', requestParameters['imageFile'] as any);
        }


        let urlPath = `/v1/avatars/{courseId}/{slot}/image`;
        urlPath = urlPath.replace(`{${"courseId"}}`, encodeURIComponent(String(requestParameters['courseId'])));
        urlPath = urlPath.replace(`{${"slot"}}`, encodeURIComponent(String(requestParameters['slot'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AvatarCreatedResponseFromJSON(jsonValue));
    }

    /**
     * Replace Avatar Image Endpoint
     */
    async replaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePost(requestParameters: ReplaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AvatarCreatedResponse> {
        const response = await this.replaceAvatarImageEndpointV1AvatarsCourseIdSlotImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
