/* tslint:disable */
/* eslint-disable */
/**
 * Service Video-Generation APIs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  GenerateRequest,
  GenerationAcceptedResponse,
  GenerationStatusResponse,
  HTTPValidationError,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GenerateRequestFromJSON,
    GenerateRequestToJSON,
    GenerationAcceptedResponseFromJSON,
    GenerationAcceptedResponseToJSON,
    GenerationStatusResponseFromJSON,
    GenerationStatusResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetGenerationStatusV1VideoPromptIdStatusGetRequest {
    promptId: string;
}

export interface RequestVideoGenerationV1VideoGeneratePostRequest {
    generateRequest: GenerateRequest;
}

/**
 * 
 */
export class VideoApi extends runtime.BaseAPI {

    /**
     * Get Generation Status
     */
    async getGenerationStatusV1VideoPromptIdStatusGetRaw(requestParameters: GetGenerationStatusV1VideoPromptIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerationStatusResponse>> {
        if (requestParameters['promptId'] == null) {
            throw new runtime.RequiredError(
                'promptId',
                'Required parameter "promptId" was null or undefined when calling getGenerationStatusV1VideoPromptIdStatusGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/video/{promptId}/status`;
        urlPath = urlPath.replace(`{${"promptId"}}`, encodeURIComponent(String(requestParameters['promptId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerationStatusResponseFromJSON(jsonValue));
    }

    /**
     * Get Generation Status
     */
    async getGenerationStatusV1VideoPromptIdStatusGet(requestParameters: GetGenerationStatusV1VideoPromptIdStatusGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerationStatusResponse> {
        const response = await this.getGenerationStatusV1VideoPromptIdStatusGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Nimmt einen einzelnen Slide entgegen (payload.voiceTrack), erwartet eine explizite Slide-Nummer (payload.slideNumber) und enqueued die Aufgabe.
     * Request Video Generation
     */
    async requestVideoGenerationV1VideoGeneratePostRaw(requestParameters: RequestVideoGenerationV1VideoGeneratePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerationAcceptedResponse>> {
        if (requestParameters['generateRequest'] == null) {
            throw new runtime.RequiredError(
                'generateRequest',
                'Required parameter "generateRequest" was null or undefined when calling requestVideoGenerationV1VideoGeneratePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/video/generate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateRequestToJSON(requestParameters['generateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerationAcceptedResponseFromJSON(jsonValue));
    }

    /**
     * Nimmt einen einzelnen Slide entgegen (payload.voiceTrack), erwartet eine explizite Slide-Nummer (payload.slideNumber) und enqueued die Aufgabe.
     * Request Video Generation
     */
    async requestVideoGenerationV1VideoGeneratePost(requestParameters: RequestVideoGenerationV1VideoGeneratePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerationAcceptedResponse> {
        const response = await this.requestVideoGenerationV1VideoGeneratePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
