# coding: utf-8

# flake8: noqa
"""
    Service Video-Generation APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from service_core.models.avatar.avatar_audio_response import AvatarAudioResponse
from service_core.models.avatar.avatar_created_response import AvatarCreatedResponse
from service_core.models.avatar.avatar_image_response import AvatarImageResponse
from service_core.models.avatar.error_model import ErrorModel
from service_core.models.avatar.generation_status_response import GenerationStatusResponse
