# coding: utf-8

"""
    Service Video-Generation APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from service_core.models.avatars import AvatarAudioResponse
from service_core.models.avatars import AvatarImageResponse
from service_core.models.avatar.course_avatar_slot import CourseAvatarSlot
from typing import Optional, Set
from typing_extensions import Self

class AvatarCreatedResponse(BaseModel):
    """
    AvatarCreatedResponse
    """ # noqa: E501
    avatar_id: StrictStr = Field(alias="avatarId")
    name: Optional[StrictStr] = None
    course_id: Optional[StrictStr] = Field(default=None, alias="courseId")
    slot: Optional[CourseAvatarSlot] = None
    created_at: datetime = Field(alias="createdAt")
    image: Optional[AvatarImageResponse] = None
    audio: Optional[AvatarAudioResponse] = None
    __properties: ClassVar[List[str]] = ["avatarId", "name", "courseId", "slot", "createdAt", "image", "audio"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AvatarCreatedResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of image
        if self.image:
            _dict['image'] = self.image.to_dict()
        # override the default output from pydantic by calling `to_dict()` of audio
        if self.audio:
            _dict['audio'] = self.audio.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if course_id (nullable) is None
        # and model_fields_set contains the field
        if self.course_id is None and "course_id" in self.model_fields_set:
            _dict['courseId'] = None

        # set to None if image (nullable) is None
        # and model_fields_set contains the field
        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        # set to None if audio (nullable) is None
        # and model_fields_set contains the field
        if self.audio is None and "audio" in self.model_fields_set:
            _dict['audio'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AvatarCreatedResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "avatarId": obj.get("avatarId"),
            "name": obj.get("name"),
            "courseId": obj.get("courseId"),
            "slot": obj.get("slot"),
            "createdAt": obj.get("createdAt"),
            "image": AvatarImageResponse.from_dict(obj["image"]) if obj.get("image") is not None else None,
            "audio": AvatarAudioResponse.from_dict(obj["audio"]) if obj.get("audio") is not None else None
        })
        return _obj


