# coding: utf-8

"""
    Service Video-Generation APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from service_core.models.avatar.user_profile import UserProfile
from typing import Optional, Set
from typing_extensions import Self

class GenerateRequest(BaseModel):
    """
    GenerateRequest
    """ # noqa: E501
    voice_track: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="voiceTrack")
    slide_number: Annotated[int, Field(strict=True, ge=0)] = Field(alias="slideNumber")
    prompt_id: StrictStr = Field(alias="promptId")
    course_id: StrictStr = Field(alias="courseId")
    user_profile: UserProfile = Field(alias="userProfile")
    slot: Optional[StrictStr] = 'default'
    __properties: ClassVar[List[str]] = ["voiceTrack", "slideNumber", "promptId", "courseId", "userProfile", "slot"]

    @field_validator('slot')
    def slot_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['default', 'beginning', 'ending']):
            raise ValueError("must be one of enum values ('default', 'beginning', 'ending')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user_profile
        if self.user_profile:
            _dict['userProfile'] = self.user_profile.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "voiceTrack": obj.get("voiceTrack"),
            "slideNumber": obj.get("slideNumber"),
            "promptId": obj.get("promptId"),
            "courseId": obj.get("courseId"),
            "userProfile": UserProfile.from_dict(obj["userProfile"]) if obj.get("userProfile") is not None else None,
            "slot": obj.get("slot") if obj.get("slot") is not None else 'default'
        })
        return _obj


