# coding: utf-8

"""
    Service Video-Generation APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from service_core.models.avatars import ErrorModel
from typing import Optional, Set
from typing_extensions import Self

class GenerationStatusResponse(BaseModel):
    """
    GenerationStatusResponse
    """ # noqa: E501
    prompt_id: StrictStr = Field(alias="promptId")
    status: StrictStr
    last_updated: datetime = Field(alias="lastUpdated")
    result_url: StrictStr = Field(alias="resultUrl")
    estimated_seconds_left: StrictInt = Field(alias="estimatedSecondsLeft")
    error: Optional[ErrorModel] = None
    __properties: ClassVar[List[str]] = ["promptId", "status", "lastUpdated", "resultUrl", "estimatedSecondsLeft", "error"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['IN_PROGRESS', 'FAILED', 'DONE']):
            raise ValueError("must be one of enum values ('IN_PROGRESS', 'FAILED', 'DONE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerationStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerationStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "promptId": obj.get("promptId"),
            "status": obj.get("status"),
            "lastUpdated": obj.get("lastUpdated"),
            "resultUrl": obj.get("resultUrl"),
            "estimatedSecondsLeft": obj.get("estimatedSecondsLeft"),
            "error": ErrorModel.from_dict(obj["error"]) if obj.get("error") is not None else None
        })
        return _obj


