# coding: utf-8

"""
    Service Video-Generation APIs

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Preferences(BaseModel):
    """
    Preferences
    """ # noqa: E501
    answer_length: Optional[StrictStr] = Field(default=None, alias="answerLength")
    language_level: Optional[StrictStr] = Field(default=None, alias="languageLevel")
    expertise_level: Optional[StrictStr] = Field(default=None, alias="expertiseLevel")
    include_pictures: Optional[StrictStr] = Field(default=None, alias="includePictures")
    __properties: ClassVar[List[str]] = ["answerLength", "languageLevel", "expertiseLevel", "includePictures"]

    @field_validator('answer_length')
    def answer_length_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['short', 'medium', 'long']):
            raise ValueError("must be one of enum values ('short', 'medium', 'long')")
        return value

    @field_validator('language_level')
    def language_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['basic', 'intermediate', 'advanced']):
            raise ValueError("must be one of enum values ('basic', 'intermediate', 'advanced')")
        return value

    @field_validator('expertise_level')
    def expertise_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['beginner', 'intermediate', 'advanced', 'expert']):
            raise ValueError("must be one of enum values ('beginner', 'intermediate', 'advanced', 'expert')")
        return value

    @field_validator('include_pictures')
    def include_pictures_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'few', 'many']):
            raise ValueError("must be one of enum values ('none', 'few', 'many')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Preferences from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if answer_length (nullable) is None
        # and model_fields_set contains the field
        if self.answer_length is None and "answer_length" in self.model_fields_set:
            _dict['answerLength'] = None

        # set to None if language_level (nullable) is None
        # and model_fields_set contains the field
        if self.language_level is None and "language_level" in self.model_fields_set:
            _dict['languageLevel'] = None

        # set to None if expertise_level (nullable) is None
        # and model_fields_set contains the field
        if self.expertise_level is None and "expertise_level" in self.model_fields_set:
            _dict['expertiseLevel'] = None

        # set to None if include_pictures (nullable) is None
        # and model_fields_set contains the field
        if self.include_pictures is None and "include_pictures" in self.model_fields_set:
            _dict['includePictures'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Preferences from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "answerLength": obj.get("answerLength"),
            "languageLevel": obj.get("languageLevel"),
            "expertiseLevel": obj.get("expertiseLevel"),
            "includePictures": obj.get("includePictures")
        })
        return _obj


