services:
  docint-service:
    container_name: docint
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # ask Krasi
    environment:
      - WEAVIATE_URL=http://docint-weaviate:28947
    ports:
      - "25565:25565"
    networks:
      - orpheus
    depends_on:
      - docint-weaviate

  docint-weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.9
    command:
      - --host
      - 0.0.0.0
      - --port
      - "28947"
      - --scheme
      - http
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      QUERY_DEFAULTS_LIMIT: "25"
      CLUSTER_HOSTNAME: "node1"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_API_BASED_MODULES: "false"
      ENABLE_MODULES: ""
      DISABLE_TELEMETRY: "true"
    ports:
      - "28947:28947"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - orpheus
    restart: unless-stopped

volumes:
  weaviate_data:

networks:
  orpheus: