/* tslint:disable */
/* eslint-disable */
/**
 * Orpheus CoreAI-Service API
 * API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PromptRequest,
  PromptResponse,
} from '../models/index';
import {
    PromptRequestFromJSON,
    PromptRequestToJSON,
    PromptResponseFromJSON,
    PromptResponseToJSON,
} from '../models/index';

export interface CreateLectureFromPromptRequest {
    promptRequest: PromptRequest;
}

/**
 * 
 */
export class CoreApi extends runtime.BaseAPI {

    /**
     * Accepts a user prompt and initiates an asynchronous job to generate lecture content. Returns a unique prompt ID to track the job.
     * Submit a prompt to generate a lecture
     */
    async createLectureFromPromptRaw(requestParameters: CreateLectureFromPromptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PromptResponse>> {
        if (requestParameters['promptRequest'] == null) {
            throw new runtime.RequiredError(
                'promptRequest',
                'Required parameter "promptRequest" was null or undefined when calling createLectureFromPrompt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/core/prompt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PromptRequestToJSON(requestParameters['promptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PromptResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a user prompt and initiates an asynchronous job to generate lecture content. Returns a unique prompt ID to track the job.
     * Submit a prompt to generate a lecture
     */
    async createLectureFromPrompt(requestParameters: CreateLectureFromPromptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PromptResponse> {
        const response = await this.createLectureFromPromptRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
