version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # This is the key line: it mounts your local 'src' folder
      # into the '/app/src' folder inside the container.
      - ./src:/app/src
    command: poetry run uvicorn service_core.main:app --reload --host 0.0.0.0 --port 8080