# docker-compose.yml

version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # This is the key line: it mounts your local 'src' folder
      # into the '/app/src' folder inside the container.
      - ./src:/app/src
    command: poetry run uvicorn src.service_core.main:app --host 0.0.0.0 --port 8000