# coding: utf-8

# flake8: noqa

"""
    Answer Generation Service API

    API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "StatusApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AvatarElementStatus",
    "AvatarElementStatusPatch",
    "Error",
    "SlideItem",
    "SlideStructure",
    "Status",
    "StatusPatch",
    "StepStatus",
]

# import apis into sdk package
from service_slides.clients.status.api.status_api import StatusApi as StatusApi

# import ApiClient
from service_slides.clients.status.api_response import ApiResponse as ApiResponse
from service_slides.clients.status.api_client import ApiClient as ApiClient
from service_slides.clients.status.configuration import Configuration as Configuration
from service_slides.clients.status.exceptions import OpenApiException as OpenApiException
from service_slides.clients.status.exceptions import ApiTypeError as ApiTypeError
from service_slides.clients.status.exceptions import ApiValueError as ApiValueError
from service_slides.clients.status.exceptions import ApiKeyError as ApiKeyError
from service_slides.clients.status.exceptions import ApiAttributeError as ApiAttributeError
from service_slides.clients.status.exceptions import ApiException as ApiException

# import models into sdk package
from service_slides.clients.status.models.avatar_element_status import AvatarElementStatus as AvatarElementStatus
from service_slides.clients.status.models.avatar_element_status_patch import AvatarElementStatusPatch as AvatarElementStatusPatch
from service_slides.clients.status.models.error import Error as Error
from service_slides.clients.status.models.slide_item import SlideItem as SlideItem
from service_slides.clients.status.models.slide_structure import SlideStructure as SlideStructure
from service_slides.clients.status.models.status import Status as Status
from service_slides.clients.status.models.status_patch import StatusPatch as StatusPatch
from service_slides.clients.status.models.step_status import StepStatus as StepStatus
