/* tslint:disable */
/* eslint-disable */
/**
 * Answer Generation Service API
 * API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromptRequest
 */
export interface PromptRequest {
    /**
     * The user's educational prompt.
     * @type {string}
     * @memberof PromptRequest
     */
    prompt: string;
    /**
     * The unique identifier of the course.
     * @type {string}
     * @memberof PromptRequest
     */
    courseId: string;
}

/**
 * Check if a given object implements the PromptRequest interface.
 */
export function instanceOfPromptRequest(value: object): value is PromptRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    return true;
}

export function PromptRequestFromJSON(json: any): PromptRequest {
    return PromptRequestFromJSONTyped(json, false);
}

export function PromptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'courseId': json['courseId'],
    };
}

export function PromptRequestToJSON(json: any): PromptRequest {
    return PromptRequestToJSONTyped(json, false);
}

export function PromptRequestToJSONTyped(value?: PromptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'courseId': value['courseId'],
    };
}

