/* tslint:disable */
/* eslint-disable */
/**
 * Orpheus CoreAI-Service API
 * API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PromptResponse
 */
export interface PromptResponse {
    /**
     * The unique ID assigned to the generation job.
     * @type {string}
     * @memberof PromptResponse
     */
    lectureId: string;
}

/**
 * Check if a given object implements the PromptResponse interface.
 */
export function instanceOfPromptResponse(value: object): value is PromptResponse {
    if (!('lectureId' in value) || value['lectureId'] === undefined) return false;
    return true;
}

export function PromptResponseFromJSON(json: any): PromptResponse {
    return PromptResponseFromJSONTyped(json, false);
}

export function PromptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromptResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'lectureId': json['lectureId'],
    };
}

export function PromptResponseToJSON(json: any): PromptResponse {
    return PromptResponseToJSONTyped(json, false);
}

export function PromptResponseToJSONTyped(value?: PromptResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lectureId': value['lectureId'],
    };
}

