/* tslint:disable */
/* eslint-disable */
/**
 * Orpheus CoreAI-Service API
 * API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SlideResponse
 */
export interface SlideResponse {
    /**
     * 
     * @type {string}
     * @memberof SlideResponse
     */
    status?: SlideResponseStatusEnum;
    /**
     * The URL to the generated slide deck. Only present if status is 'completed'.
     * @type {string}
     * @memberof SlideResponse
     */
    slidesUrl?: string;
}


/**
 * @export
 */
export const SlideResponseStatusEnum = {
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type SlideResponseStatusEnum = typeof SlideResponseStatusEnum[keyof typeof SlideResponseStatusEnum];


/**
 * Check if a given object implements the SlideResponse interface.
 */
export function instanceOfSlideResponse(value: object): value is SlideResponse {
    return true;
}

export function SlideResponseFromJSON(json: any): SlideResponse {
    return SlideResponseFromJSONTyped(json, false);
}

export function SlideResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlideResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'slidesUrl': json['slidesUrl'] == null ? undefined : json['slidesUrl'],
    };
}

export function SlideResponseToJSON(json: any): SlideResponse {
    return SlideResponseToJSONTyped(json, false);
}

export function SlideResponseToJSONTyped(value?: SlideResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'slidesUrl': value['slidesUrl'],
    };
}

