# coding: utf-8

# flake8: noqa
"""
Orpheus Slide-postprocessing-Service API

API for the Orpheus slide postprocessing and delivery. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository).

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from service_slides.clients.postprocessing.models.error import Error
from service_slides.clients.postprocessing.models.get_slideset200_response import (
    GetSlideset200Response,
)
from service_slides.clients.postprocessing.models.list_slidesets200_response_inner import (
    ListSlidesets200ResponseInner,
)
from service_slides.clients.postprocessing.models.slideset_with_id import SlidesetWithId
from service_slides.clients.postprocessing.models.slideset_with_id_assets_inner import (
    SlidesetWithIdAssetsInner,
)
from service_slides.clients.postprocessing.models.store_slideset_request import StoreSlidesetRequest
from service_slides.clients.postprocessing.models.upload_accepted_response import (
    UploadAcceptedResponse,
)
