# coding: utf-8

"""
Orpheus Slide-postprocessing-Service API

API for the Orpheus slide postprocessing and delivery. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository).

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from service_slides.clients.postprocessing.models.slideset_with_id_assets_inner import (
    SlidesetWithIdAssetsInner,
)


class SlidesetWithId(BaseModel):
    """
    SlidesetWithId
    """  # noqa: E501

    prompt_id: StrictStr = Field(
        description="Unique identifier of the lecture to which the slides will belong. ",
        alias="promptId",
    )
    slideset: StrictStr = Field(
        description="Markdown source code for the slideset. Has to conform to sli.dev syntax. "
    )
    user: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Schemaless additional information about the user (e.g. preferences regarding slide style).",
    )
    assets: List[SlidesetWithIdAssetsInner] = Field(
        description="Additional files: images, PDFs, graphs, tables, listings, equations. Use multiple entries for multiple files. May be empty."
    )
    __properties: ClassVar[List[str]] = ["promptId", "slideset", "user", "assets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SlidesetWithId from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in assets (list)
        _items = []
        if self.assets:
            for _item_assets in self.assets:
                if _item_assets:
                    _items.append(_item_assets.to_dict())
            _dict["assets"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SlidesetWithId from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "promptId": obj.get("promptId"),
                "slideset": obj.get("slideset"),
                "user": obj.get("user"),
                "assets": [SlidesetWithIdAssetsInner.from_dict(_item) for _item in obj["assets"]]
                if obj.get("assets") is not None
                else None,
            }
        )
        return _obj
