# coding: utf-8

"""
Orpheus Slide-Postprocessing-Service API

API for the Orpheus slide postprocessing and delivery. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository).

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from fastapi import FastAPI

from service_slides_postprocessing.apis.postprocessing_api import router as PostprocessingApiRouter

app = FastAPI(
    title="Orpheus Slide-Postprocessing-Service API",
    description="API for the Orpheus slide postprocessing and delivery. From the repository: \&quot;The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\&quot; License: MIT (see repository). ",
    version="0.1.0",
)

app.include_router(PostprocessingApiRouter)
