/* tslint:disable */
/* eslint-disable */
/**
 * Answer Generation Service API
 * API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepStatus } from './StepStatus';
import {
    StepStatusFromJSON,
    StepStatusFromJSONTyped,
    StepStatusToJSON,
    StepStatusToJSONTyped,
} from './StepStatus';

/**
 * 
 * @export
 * @interface AvatarElementStatus
 */
export interface AvatarElementStatus {
    /**
     * 
     * @type {StepStatus}
     * @memberof AvatarElementStatus
     */
    audio?: StepStatus;
    /**
     * 
     * @type {StepStatus}
     * @memberof AvatarElementStatus
     */
    video?: StepStatus;
}



/**
 * Check if a given object implements the AvatarElementStatus interface.
 */
export function instanceOfAvatarElementStatus(value: object): value is AvatarElementStatus {
    return true;
}

export function AvatarElementStatusFromJSON(json: any): AvatarElementStatus {
    return AvatarElementStatusFromJSONTyped(json, false);
}

export function AvatarElementStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarElementStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'audio': json['audio'] == null ? undefined : StepStatusFromJSON(json['audio']),
        'video': json['video'] == null ? undefined : StepStatusFromJSON(json['video']),
    };
}

export function AvatarElementStatusToJSON(json: any): AvatarElementStatus {
    return AvatarElementStatusToJSONTyped(json, false);
}

export function AvatarElementStatusToJSONTyped(value?: AvatarElementStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'audio': StepStatusToJSON(value['audio']),
        'video': StepStatusToJSON(value['video']),
    };
}

