/* tslint:disable */
/* eslint-disable */
/**
 * Answer Generation Service API
 * API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlideStructure } from './SlideStructure';
import {
    SlideStructureFromJSON,
    SlideStructureFromJSONTyped,
    SlideStructureToJSON,
    SlideStructureToJSONTyped,
} from './SlideStructure';
import type { StepStatus } from './StepStatus';
import {
    StepStatusFromJSON,
    StepStatusFromJSONTyped,
    StepStatusToJSON,
    StepStatusToJSONTyped,
} from './StepStatus';

/**
 * 
 * @export
 * @interface StatusPatch
 */
export interface StatusPatch {
    /**
     * 
     * @type {StepStatus}
     * @memberof StatusPatch
     */
    stepUnderstanding?: StepStatus;
    /**
     * 
     * @type {StepStatus}
     * @memberof StatusPatch
     */
    stepLookup?: StepStatus;
    /**
     * 
     * @type {StepStatus}
     * @memberof StatusPatch
     */
    stepLectureScriptGeneration?: StepStatus;
    /**
     * 
     * @type {StepStatus}
     * @memberof StatusPatch
     */
    stepSlideStructureGeneration?: StepStatus;
    /**
     * 
     * @type {number}
     * @memberof StatusPatch
     */
    stepSlideGeneration?: number;
    /**
     * 
     * @type {StepStatus}
     * @memberof StatusPatch
     */
    stepSlidePostprocessing?: StepStatus;
    /**
     * 
     * @type {object}
     * @memberof StatusPatch
     */
    stepsAvatarGeneration?: object;
    /**
     * 
     * @type {string}
     * @memberof StatusPatch
     */
    lectureSummary?: string;
    /**
     * 
     * @type {SlideStructure}
     * @memberof StatusPatch
     */
    slideStructure?: SlideStructure;
}



/**
 * Check if a given object implements the StatusPatch interface.
 */
export function instanceOfStatusPatch(value: object): value is StatusPatch {
    return true;
}

export function StatusPatchFromJSON(json: any): StatusPatch {
    return StatusPatchFromJSONTyped(json, false);
}

export function StatusPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'stepUnderstanding': json['stepUnderstanding'] == null ? undefined : StepStatusFromJSON(json['stepUnderstanding']),
        'stepLookup': json['stepLookup'] == null ? undefined : StepStatusFromJSON(json['stepLookup']),
        'stepLectureScriptGeneration': json['stepLectureScriptGeneration'] == null ? undefined : StepStatusFromJSON(json['stepLectureScriptGeneration']),
        'stepSlideStructureGeneration': json['stepSlideStructureGeneration'] == null ? undefined : StepStatusFromJSON(json['stepSlideStructureGeneration']),
        'stepSlideGeneration': json['stepSlideGeneration'] == null ? undefined : json['stepSlideGeneration'],
        'stepSlidePostprocessing': json['stepSlidePostprocessing'] == null ? undefined : StepStatusFromJSON(json['stepSlidePostprocessing']),
        'stepsAvatarGeneration': json['stepsAvatarGeneration'] == null ? undefined : json['stepsAvatarGeneration'],
        'lectureSummary': json['lectureSummary'] == null ? undefined : json['lectureSummary'],
        'slideStructure': json['slideStructure'] == null ? undefined : SlideStructureFromJSON(json['slideStructure']),
    };
}

export function StatusPatchToJSON(json: any): StatusPatch {
    return StatusPatchToJSONTyped(json, false);
}

export function StatusPatchToJSONTyped(value?: StatusPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stepUnderstanding': StepStatusToJSON(value['stepUnderstanding']),
        'stepLookup': StepStatusToJSON(value['stepLookup']),
        'stepLectureScriptGeneration': StepStatusToJSON(value['stepLectureScriptGeneration']),
        'stepSlideStructureGeneration': StepStatusToJSON(value['stepSlideStructureGeneration']),
        'stepSlideGeneration': value['stepSlideGeneration'],
        'stepSlidePostprocessing': StepStatusToJSON(value['stepSlidePostprocessing']),
        'stepsAvatarGeneration': value['stepsAvatarGeneration'],
        'lectureSummary': value['lectureSummary'],
        'slideStructure': SlideStructureToJSON(value['slideStructure']),
    };
}

