/* tslint:disable */
/* eslint-disable */
/**
 * Answer Generation Service API
 * API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive prompt videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StepStatus = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Done: 'DONE',
    Failed: 'FAILED'
} as const;
export type StepStatus = typeof StepStatus[keyof typeof StepStatus];


export function instanceOfStepStatus(value: any): boolean {
    for (const key in StepStatus) {
        if (Object.prototype.hasOwnProperty.call(StepStatus, key)) {
            if (StepStatus[key as keyof typeof StepStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StepStatusFromJSON(json: any): StepStatus {
    return StepStatusFromJSONTyped(json, false);
}

export function StepStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepStatus {
    return json as StepStatus;
}

export function StepStatusToJSON(value?: StepStatus | null): any {
    return value as any;
}

export function StepStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): StepStatus {
    return value as StepStatus;
}

