/* tslint:disable */
/* eslint-disable */
/**
 * Lecture Ingestion Service API
 * API for the Orpheus document intelligence orchestration. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageObject
 */
export interface ImageObject {
    /**
     * Base64-encoded image.
     * @type {string}
     * @memberof ImageObject
     */
    image?: string;
    /**
     * Short description of the image.
     * @type {string}
     * @memberof ImageObject
     */
    description?: string;
}

/**
 * Check if a given object implements the ImageObject interface.
 */
export function instanceOfImageObject(value: object): value is ImageObject {
    return true;
}

export function ImageObjectFromJSON(json: any): ImageObject {
    return ImageObjectFromJSONTyped(json, false);
}

export function ImageObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageObject {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'] == null ? undefined : json['image'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ImageObjectToJSON(json: any): ImageObject {
    return ImageObjectToJSONTyped(json, false);
}

export function ImageObjectToJSONTyped(value?: ImageObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'description': value['description'],
    };
}

