/* tslint:disable */
/* eslint-disable */
/**
 * Lecture Ingestion Service API
 * API for the Orpheus document intelligence orchestration. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoUploadResponse
 */
export interface VideoUploadResponse {
    /**
     * The ID of the stored video.
     * @type {string}
     * @memberof VideoUploadResponse
     */
    videoId: string;
}

/**
 * Check if a given object implements the VideoUploadResponse interface.
 */
export function instanceOfVideoUploadResponse(value: object): value is VideoUploadResponse {
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    return true;
}

export function VideoUploadResponseFromJSON(json: any): VideoUploadResponse {
    return VideoUploadResponseFromJSONTyped(json, false);
}

export function VideoUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['videoId'],
    };
}

export function VideoUploadResponseToJSON(json: any): VideoUploadResponse {
    return VideoUploadResponseToJSONTyped(json, false);
}

export function VideoUploadResponseToJSONTyped(value?: VideoUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'videoId': value['videoId'],
    };
}

