openapi: 3.1.0
info:
  title: Service Video-Generation APIs
  version: "0.1"
  description: |
    API for the Orpheus video generation.
    From the repository: "The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences."
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"
  termsOfService: "https://github.com/fa25genai/orpheus"
  contact:
    name: "Orpheus Project"
    url: "https://github.com/fa25genai/orpheus/issues/new"

servers:
  - url: "http://localhost:8080"
    description: "Local development"

tags:
  - name: video
    description: "Endpoints for video generation, retrieval and status"
  - name: avatar
    description: "Endpoints for creating avatars and uploading avatar images"

paths:
  /v1/video/generate:
    post:
      tags:
        - video
      summary: "Request generation of a video, given the written text"
      description: |
        Accepts an array of messages written in fluent text. They are divided by slides.
        Accepts a courseId used to identify and pull the correct audio and image samples for generating the requested professor avatar.
        Accepts a promptId, a unique identifier for the generated video and slides.
        Accepts user profile information for adapting the video to the specific user needs.
      operationId: requestVideoGeneration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - slideMessages
                - promptId
                - courseId
                - userProfile
              properties:
                slideMessages:
                  type: array
                  description: "Per-slide text blocks in order."
                  minItems: 1
                  items:
                    type: string
                    description: "The spoken/script text for one slide."
                    minLength: 1
                promptId:
                  type: string
                  format: uuid
                  description: >
                    Unique identifier of the lecture to which the slides will belong.
                courseId:
                  type: string
                  description: "Course ID used to identify the correct professor/avatar resources."
                userProfile:
                  $ref: "#/components/schemas/UserProfile"
      responses:
        "202":
          description: "Request accepted — generation started. Returns request metadata and immediate structure summary."
          headers:
            Location:
              description: "URL to query the status of the generation (status endpoint)."
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerationAcceptedResponse"
              examples:
                accepted:
                  summary: "Example accepted response"
                  value:
                    promptId: "3a6d2f2e-6b1a-4b0b-9d7e-2f5a2a4c1b9e"
                    createdAt: "2025-09-22T09:12:33Z"
        "400":
          description: "Malformed request."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: "Server error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/video/{promptId}/status:
    get:
      tags:
        - video
      summary: "Return current generation status (polling)"
      operationId: getGenerationResult
      parameters:
        - name: promptId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: "The promptId returned by /v1/video/generate"
      responses:
        "200":
          description: "Current generation status (may be IN_PROGRESS, DONE, or FAILED)."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenerationStatusResponse"
              examples:
                done:
                  value:
                    promptId: "0f2f9d77-8e67-4c5a-9c5d-0f2b9a3a1e12"
                    status: "DONE"
                    lastUpdated: "2025-09-22T09:41:00Z"
                    resultUrl: "https://cdn.example.com/videos/0f2f9d77.mp4"
                failed:
                  value:
                    promptId: "0f2f9d77-8e67-4c5a-9c5d-0f2b9a3a1e12"
                    status: "FAILED"
                    lastUpdated: "2025-09-22T09:41:00Z"
                    error:
                      code: "TTS_ENGINE_ERROR"
                      message: "Text-to-speech conversion failed."
        "404":
          description: "Request not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/avatars:
    post:
      tags:
        - avatar
      summary: "Create a new avatar"
      description: |
        Creates a new avatar record. Optionally, an image file can be uploaded at the same time.
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: "Avatar created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvatarCreatedResponse"

  /v1/avatars/{avatarId}/images:
    post:
      tags:
        - avatar
      summary: "Add an image to an existing avatar"
      parameters:
        - name: avatarId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: "Image added successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AvatarImageResponse"
        "404":
          description: "Avatar not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  schemas:
    UserProfile:
      type: object
      description: "Information about the user and their preferences."
      required:
        - id
        - role
        - language
      properties:
        id:
          type: string
          description: "Unique identifier of the user."
        role:
          type: string
          enum: [ student, instructor ]
          description: "User's role."
        language:
          type: string
          enum: [ german, english ]
          description: "Primary language."
        preferences:
          type: object
          description: "Generation/presentation preferences."
          properties:
            answerLength:
              type: string
              enum: [ short, medium, long ]
            languageLevel:
              type: string
              enum: [ basic, intermediate, advanced ]
            expertiseLevel:
              type: string
              enum: [ beginner, intermediate, advanced, expert ]
            includePictures:
              type: string
              enum: [ none, few, many ]
        enrolledCourses:
          type: array
          description: "Course IDs the user is enrolled in."
          items:
            type: string

    GenerationAcceptedResponse:
      type: object
      description: "Returned immediately after generation request accepted"
      properties:
        promptId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
          
    GenerationStatusResponse:
      type: object
      properties:
        promptId: { type: string, format: uuid }
        status: { type: string, enum: [ IN_PROGRESS, FAILED, DONE ] }
        lastUpdated: { type: string, format: date-time }
        resultUrl: { type: string, format: uri, description: "URL even if not ready" }
        estimatedSecondsLeft: { type: integer, minimum: 0, description: "0 when DONE/FAILED" }
        error: { $ref: "#/components/schemas/Error" }

    AvatarCreatedResponse:
      type: object
      properties:
        avatarId:
          type: string
          format: uuid
        image:
          type: object
          nullable: true
          properties:
            id:
              type: string
              format: uuid
            filePath:
              type: string
            mimeType:
              type: string
            sizeBytes:
              type: integer
            createdAt:
              type: string
              format: date-time

    AvatarImageResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        avatarId:
          type: string
          format: uuid
        filePath:
          type: string
        mimeType:
          type: string
        sizeBytes:
          type: integer
        createdAt:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

externalDocs:
  description: "Project repository and README"
  url: "https://github.com/fa25genai/orpheus"

