/* tslint:disable */
/* eslint-disable */
/**
 * Slide Generation Service API
 * API for the Orpheus slide generation. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerationStatusResponse
 */
export interface GenerationStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    promptId?: string;
    /**
     * Job status
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    status?: GenerationStatusResponseStatusEnum;
    /**
     * Total amount of pages that have to be generated
     * @type {number}
     * @memberof GenerationStatusResponse
     */
    totalPages?: number;
    /**
     * Amount of generated pages at the last point of update
     * @type {number}
     * @memberof GenerationStatusResponse
     */
    generatedPages?: number;
    /**
     * 
     * @type {Date}
     * @memberof GenerationStatusResponse
     */
    lastUpdated?: Date;
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    webUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GenerationStatusResponse
     */
    pdfUrl?: string;
    /**
     * 
     * @type {Error}
     * @memberof GenerationStatusResponse
     */
    error?: Error;
}


/**
 * @export
 */
export const GenerationStatusResponseStatusEnum = {
    InProgress: 'IN_PROGRESS',
    Failed: 'FAILED',
    Done: 'DONE'
} as const;
export type GenerationStatusResponseStatusEnum = typeof GenerationStatusResponseStatusEnum[keyof typeof GenerationStatusResponseStatusEnum];


/**
 * Check if a given object implements the GenerationStatusResponse interface.
 */
export function instanceOfGenerationStatusResponse(value: object): value is GenerationStatusResponse {
    return true;
}

export function GenerationStatusResponseFromJSON(json: any): GenerationStatusResponse {
    return GenerationStatusResponseFromJSONTyped(json, false);
}

export function GenerationStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'promptId': json['promptId'] == null ? undefined : json['promptId'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'generatedPages': json['generatedPages'] == null ? undefined : json['generatedPages'],
        'lastUpdated': json['lastUpdated'] == null ? undefined : (new Date(json['lastUpdated'])),
        'webUrl': json['webUrl'] == null ? undefined : json['webUrl'],
        'pdfUrl': json['pdfUrl'] == null ? undefined : json['pdfUrl'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GenerationStatusResponseToJSON(json: any): GenerationStatusResponse {
    return GenerationStatusResponseToJSONTyped(json, false);
}

export function GenerationStatusResponseToJSONTyped(value?: GenerationStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'promptId': value['promptId'],
        'status': value['status'],
        'totalPages': value['totalPages'],
        'generatedPages': value['generatedPages'],
        'lastUpdated': value['lastUpdated'] == null ? undefined : ((value['lastUpdated']).toISOString()),
        'webUrl': value['webUrl'],
        'pdfUrl': value['pdfUrl'],
        'error': value['error'],
    };
}

