/* tslint:disable */
/* eslint-disable */
/**
 * Slide Generation Service API
 * API for the Orpheus slide generation. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestSlideGenerationRequestAssetsInner
 */
export interface RequestSlideGenerationRequestAssetsInner {
    /**
     * File name of the asset
     * @type {string}
     * @memberof RequestSlideGenerationRequestAssetsInner
     */
    name?: string;
    /**
     * Plain text description of the asset/it's contents
     * @type {string}
     * @memberof RequestSlideGenerationRequestAssetsInner
     */
    assetDescription: string;
    /**
     * MIME-Type name of the file type (e.g. image/png)
     * @type {string}
     * @memberof RequestSlideGenerationRequestAssetsInner
     */
    mimeType: string;
    /**
     * Base64 encoded raw data of the asset
     * @type {string}
     * @memberof RequestSlideGenerationRequestAssetsInner
     */
    data: string;
}

/**
 * Check if a given object implements the RequestSlideGenerationRequestAssetsInner interface.
 */
export function instanceOfRequestSlideGenerationRequestAssetsInner(value: object): value is RequestSlideGenerationRequestAssetsInner {
    if (!('assetDescription' in value) || value['assetDescription'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RequestSlideGenerationRequestAssetsInnerFromJSON(json: any): RequestSlideGenerationRequestAssetsInner {
    return RequestSlideGenerationRequestAssetsInnerFromJSONTyped(json, false);
}

export function RequestSlideGenerationRequestAssetsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestSlideGenerationRequestAssetsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'assetDescription': json['assetDescription'],
        'mimeType': json['mimeType'],
        'data': json['data'],
    };
}

export function RequestSlideGenerationRequestAssetsInnerToJSON(json: any): RequestSlideGenerationRequestAssetsInner {
    return RequestSlideGenerationRequestAssetsInnerToJSONTyped(json, false);
}

export function RequestSlideGenerationRequestAssetsInnerToJSONTyped(value?: RequestSlideGenerationRequestAssetsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'assetDescription': value['assetDescription'],
        'mimeType': value['mimeType'],
        'data': value['data'],
    };
}

