/* tslint:disable */
/* eslint-disable */
/**
 * Orpheus Slide-Service API
 * API for the Orpheus slide generation. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One slide entry in the structure summary
 * @export
 * @interface SlideItem
 */
export interface SlideItem {
    /**
     * Human readable text, describing which lecture contents will be contained in the slide
     * @type {string}
     * @memberof SlideItem
     */
    content?: string;
}

/**
 * Check if a given object implements the SlideItem interface.
 */
export function instanceOfSlideItem(value: object): value is SlideItem {
    return true;
}

export function SlideItemFromJSON(json: any): SlideItem {
    return SlideItemFromJSONTyped(json, false);
}

export function SlideItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlideItem {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function SlideItemToJSON(json: any): SlideItem {
    return SlideItemToJSONTyped(json, false);
}

export function SlideItemToJSONTyped(value?: SlideItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

