/* tslint:disable */
/* eslint-disable */
/**
 * Slide Generation Service API
 * API for the Orpheus slide generation. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlideItem } from './SlideItem';
import {
    SlideItemFromJSON,
    SlideItemFromJSONTyped,
    SlideItemToJSON,
    SlideItemToJSONTyped,
} from './SlideItem';

/**
 * High-level structure of the slide deck returned early for UI and navigation
 * @export
 * @interface SlideStructure
 */
export interface SlideStructure {
    /**
     * 
     * @type {Array<SlideItem>}
     * @memberof SlideStructure
     */
    pages?: Array<SlideItem>;
}

/**
 * Check if a given object implements the SlideStructure interface.
 */
export function instanceOfSlideStructure(value: object): value is SlideStructure {
    return true;
}

export function SlideStructureFromJSON(json: any): SlideStructure {
    return SlideStructureFromJSONTyped(json, false);
}

export function SlideStructureFromJSONTyped(json: any, ignoreDiscriminator: boolean): SlideStructure {
    if (json == null) {
        return json;
    }
    return {
        
        'pages': json['pages'] == null ? undefined : ((json['pages'] as Array<any>).map(SlideItemFromJSON)),
    };
}

export function SlideStructureToJSON(json: any): SlideStructure {
    return SlideStructureToJSONTyped(json, false);
}

export function SlideStructureToJSONTyped(value?: SlideStructure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pages': value['pages'] == null ? undefined : ((value['pages'] as Array<any>).map(SlideItemToJSON)),
    };
}

