# coding: utf-8

# flake8: noqa

"""
    Orpheus Slide-postprocessing-Service API

    API for the Orpheus slide postprocessing and delivery. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "PostprocessingApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Error",
    "GetSlideset200Response",
    "ListSlidesets200ResponseInner",
    "SlidesetWithId",
    "SlidesetWithIdAssetsInner",
    "StoreSlidesetRequest",
    "UploadAcceptedResponse",
]

# import apis into sdk package
from service_slides.clients.postprocessing.api.postprocessing_api import PostprocessingApi as PostprocessingApi

# import ApiClient
from service_slides.clients.postprocessing.api_response import ApiResponse as ApiResponse
from service_slides.clients.postprocessing.api_client import ApiClient as ApiClient
from service_slides.clients.postprocessing.configuration import Configuration as Configuration
from service_slides.clients.postprocessing.exceptions import OpenApiException as OpenApiException
from service_slides.clients.postprocessing.exceptions import ApiTypeError as ApiTypeError
from service_slides.clients.postprocessing.exceptions import ApiValueError as ApiValueError
from service_slides.clients.postprocessing.exceptions import ApiKeyError as ApiKeyError
from service_slides.clients.postprocessing.exceptions import ApiAttributeError as ApiAttributeError
from service_slides.clients.postprocessing.exceptions import ApiException as ApiException

# import models into sdk package
from service_slides.clients.postprocessing.models.error import Error as Error
from service_slides.clients.postprocessing.models.get_slideset200_response import GetSlideset200Response as GetSlideset200Response
from service_slides.clients.postprocessing.models.list_slidesets200_response_inner import ListSlidesets200ResponseInner as ListSlidesets200ResponseInner
from service_slides.clients.postprocessing.models.slideset_with_id import SlidesetWithId as SlidesetWithId
from service_slides.clients.postprocessing.models.slideset_with_id_assets_inner import SlidesetWithIdAssetsInner as SlidesetWithIdAssetsInner
from service_slides.clients.postprocessing.models.store_slideset_request import StoreSlidesetRequest as StoreSlidesetRequest
from service_slides.clients.postprocessing.models.upload_accepted_response import UploadAcceptedResponse as UploadAcceptedResponse
