name: Slides Lint & Typecheck

on:
  pull_request:
    paths:
      - 'slides/**'
  push:
    paths:
      - 'slides/**'

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: slides
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry 2.2
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi

      - name: Ruff Lint
        run: poetry run ruff check .

      - name: MyPy Type Check
        run: poetry run mypy src

