# coding: utf-8

"""
    Orpheus CoreAI-Service API

    API for the Orpheus core orchestration. From the repository: \"The Orpheus System transforms static slides into interactive lecture videos with lifelike professor avatars, combining expressive narration, visual presence, and dynamic content to create engaging, personalized learning experiences.\" License: MIT (see repository). 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from openapi_server.models.user_profile_preferences import UserProfilePreferences
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UserProfile(BaseModel):
    """
    UserProfile
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="Unique identifier for the user.")
    role: Optional[StrictStr] = None
    language: Optional[StrictStr] = None
    preferences: Optional[UserProfilePreferences] = None
    enrolled_courses: Optional[List[StrictStr]] = Field(default=None, alias="enrolledCourses")
    __properties: ClassVar[List[str]] = ["id", "role", "language", "preferences", "enrolledCourses"]

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('student', 'instructor',):
            raise ValueError("must be one of enum values ('student', 'instructor')")
        return value

    @field_validator('language')
    def language_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('german', 'english',):
            raise ValueError("must be one of enum values ('german', 'english')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of preferences
        if self.preferences:
            _dict['preferences'] = self.preferences.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UserProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "role": obj.get("role"),
            "language": obj.get("language"),
            "preferences": UserProfilePreferences.from_dict(obj.get("preferences")) if obj.get("preferences") is not None else None,
            "enrolledCourses": obj.get("enrolledCourses")
        })
        return _obj


